version: '3.5'
services:
  ipmi-exporter:
    image: darren00/ipmi-exporter
    restart: always
    environment:
      IPMIUSER: "root"                      # default ipmi user
      IPMIPASSWORD: "YourPassword"          # default ipmi password
    volumes:
      - ./ipmi_remote.yml:/config.yml:ro    # replace with your own config
    ports:
      - 9290:9290
