version: '3.5'
services:
  ipmi_exporter:
    build:
      context: .
    environment:
      IPMIUSER: "root"                      # default ipmi user
      IPMIPASSWORD: "YourPassword"          # default ipmi password
    volumes:
      - ./ipmi_remote.yml:/config.yml:ro    # replace with your own config
    ports:
      - 9290:9290                           # bind on 0.0.0.0
      # - 127.0.0.1:9290:9290               # or bind to specific interface
    hostname: ipmi_exporter_docker
